name: Automated Tests
on:
  push:

env:
  environment: dev

jobs:
  setting_branch:
    name: Set Parameter
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.variables.outputs.environment }}
    steps:
      - name: Variables
        id: variables
        run: |
          echo "::set-output name=environment::dev" >> "$GITHUB_OUTPUT"

  automated_tests:
    needs: [setting_branch]
    uses: github.com:ralvarez-globant/callee/.github/workflows/callee.yml@main
    with:
      environment: "${{ needs.setting_branch.outputs.environment }}"
